GBHBookStoreAPI/Controllers/DocumentationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GBHBookStoreAPI.Controllers
{
    public class DocumentationController : Controller
    {
        // GET: Documentation
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Books()
        {
            return View();
        }

        public ActionResult Categories()
        {
            return View();
        }

        public ActionResult Authors()
        {
            return View();
        }

        public ActionResult Formats()
        {
            return View();
        }

        public ActionResult Languages()
        {
            return View();
        }
    }
}

GBHBookStoreAPI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Soluciones GBH - BookStore API", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Books", "Books", "Documentation", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Categories", "Categories", "Documentation", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Authors", "Authors", "Documentation", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Formats", "Formats", "Documentation", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Languages", "Languages", "Documentation", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Wellington Villegas for Soluciones GBH</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>